### ISSUE TITLE
Verifying images on public repo

### ISSUE THREAD

**Issue by davedoesdev** [cloudius-systems/capstan#144]
The public repo on S3 seems to use HTTP.
Are the images verified for integrity when pulled?
Is there a way to switch to using HTTPS?

**Comment by penberg** [comment]
@davedoesdev I switched Capstan to use HTTPS by default now. There's no image integrity checks so I'm leaving the issue open for now.

**Comment by davedoesdev** [comment]
@penberg  Thanks. I can confirm it goes over HTTPS now. Just one slight thing: When I don't have CA certs installed, I get the following error from Capstan:

```shell
~ # capstan search node
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x46b3eb]

goroutine 1 [running]:
github.com/cloudius-systems/capstan/util.ListImagesRemote(0xc20800b110, 0x25, 0x7fff2c17eb74, 0x4)
	/home/install/gopath/src/github.com/cloudius-systems/capstan/util/s3_repository.go:113 +0x44b
main.func·008(0xc2080801c0)
	/home/install/gopath/src/github.com/cloudius-systems/capstan/capstan.go:217 +0xde
github.com/codegangsta/cli.Command.Run(0x807550, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x844050, 0x16, 0x0, ...)
	/home/install/gopath/src/github.com/codegangsta/cli/command.go:118 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc208082000, 0xc20800a000, 0x3, 0x3, 0x0, 0x0)
	/home/install/gopath/src/github.com/codegangsta/cli/app.go:154 +0xd04
main.main()
	/home/install/gopath/src/github.com/cloudius-systems/capstan/capstan.go:253 +0x1fe3

goroutine 10 [sleep]:
net.func·019()
	/home/install/go/src/net/dnsclient_unix.go:240 +0x5a
created by net.loadConfig
	/home/install/go/src/net/dnsclient_unix.go:269 +0x20c
```

However, Docker (also a Go app) displays a nice message:

```shell
~ # docker search ubuntu
FATA[0000] Error response from daemon: Get https://index.docker.io/v1/search?q=ubuntu: x509: failed to load system roots and no roots provided 
```

So just a gentle feature request to do the same.

**Comment by penberg** [comment]
@davedoesdev The problem was lack of error handling for the HTTP operations. Does f88017d638b5fd0b107c766d7ba9a611595d3504 fix it for you?

**Comment by davedoesdev** [comment]
Yes, that fixes it - thanks.
